[package]
name = "tang-example-raw"
version = "0.1.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies.futures-preview]
version = "0.3.0-alpha.18"
features = [ "nightly", "async-await" ]

[dependencies.tokio]
version = "0.2.0-alpha.5"
default-features = false
features = [ "io", "codec", "fs" ]

[dependencies.tokio-postgres]
git = "https://github.com/sfackler/rust-postgres"

[dependencies.redis]
git = "https://github.com/Marwes/redis-rs.git"
branch = "std_future"

[dependencies.tang-rs]
path = "../../"