[package]
name = "tang-rs"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"
description = "A light weight asynchronous connection pool runs on tokio"
keywords = ["database", "async", "pool"]
license = "MIT"
exclude = ["examples/*"]
repository = "https://github.com/fakeshadow/tang_rs"
readme= "README.md"

[lib]
name = "tang_rs"
path = "src/lib.rs"

[features]
default = ["tokio-postgres", "redis"]
actix-web = ["tokio-timer01", "tokio-postgres", "redis"]

[workspace]
members = [
  "examples/actix-web-example",
  "examples/rocket",
  "examples/raw",
]

[dependencies.futures-util-preview]
version = "=0.3.0-alpha.19"
default-features = false
features = [ "std", "compat" ]

[dependencies.mongodb]
optional = true
version = "0.4.0"

[dependencies.slab]
version = "0.4.2"

[dependencies.tokio-executor]
version = "=0.2.0-alpha.6"

[dependencies.tokio-timer]
version = "=0.3.0-alpha.6"

[dependencies.tokio-timer01]
package= "tokio-timer"
version = "=0.2.11"
optional = true

[dependencies.tokio-postgres]
optional = true
version = "0.5.0-alpha.1"

[dependencies.redis]
optional = true
git = "https://github.com/Marwes/redis-rs"
branch = "async_await_api"
default-features = false
features = [ "executor" ]
