[package]
name = "tang-rs"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"
description = "A light weight asynchronous connection pool runs on tokio"
keywords = ["database", "async", "pool"]
license = "MIT"
exclude = ["examples/*"]
repository = "https://github.com/fakeshadow/tang_rs"
readme= "README.md"

[lib]
name = "tang_rs"
path = "src/lib.rs"

[features]
default = []

[workspace]
members = [
  "examples/actix-web-example",
  "examples/rocket",
  "examples/raw",
]

[dependencies.futures-util]
version = "0.3.4"
default-features = false

[dependencies.mongodb]
optional = true
version = "0.4.0"

[dependencies.tokio]
version = "0.2.16"
default-features = false
features = [ "rt-core", "time" ]

[dependencies.tokio-postgres]
optional = true
version = "0.5.3"

[dependencies.redis]
optional = true
version = "0.15.1"
default-features = false
features = ["tokio-rt-core"]

[dev-dependencies.tokio]
version = "0.2.16"
features = ["macros"]
