[package]
name = "tang-rs"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"
description = "A tokio-postgres Connection pool"
keywords = ["database", "async", "tokio-postgres"]
license = "MIT"
exclude = ["examples/*"]
repository = "https://github.com/fakeshadow/tang_rs"
readme= "README.md"

[lib]
name = "tang_rs"
path = "src/lib.rs"

[features]
default = [ "tokio-postgres", "redis" ]
actix-web = [ "tokio-timer01", "actix-rt", "tokio-postgres", "redis" ]
with-mongodb = [ "mongodb" ]
with-tokio-postgres = [ "tokio-postgres" ]
with-redis = [ "redis" ]

[workspace]
members = [
  "examples/actix-web-example",
  "examples/rocket",
  "examples/raw",
]

[dependencies.actix-rt]
version = "0.2.5"
optional = true

[dependencies.futures-preview]
version = "=0.3.0-alpha.19"
features = [ "compat", "async-await" ]

[dependencies.mongodb]
optional = true
version = "0.4.0"

[dependencies.slab]
version = "0.4.2"

[dependencies.tokio-executor]
version = "=0.2.0-alpha.6"

[dependencies.tokio-timer]
version = "=0.3.0-alpha.6"

[dependencies.tokio-timer01]
package= "tokio-timer"
version = "=0.2.11"
optional = true

[dependencies.tokio-postgres]
optional = true
git = "https://github.com/sfackler/rust-postgres"

[dependencies.redis]
optional = true
git = "https://github.com/fakeshadow/redis-rs"
branch = "async_await_api"