[package]
name = "tang-rs"
version = "0.1.2"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"
description = "A light weight asynchronous connection pool"
keywords = ["async", "pool"]
license = "MIT"
exclude = ["examples/*"]
repository = "https://github.com/fakeshadow/tang_rs"
readme= "README.md"

[lib]
name = "tang_rs"
path = "src/lib.rs"

[features]
default = []

[workspace]
members = [
  "examples/actix-web-example",
  "examples/basic",
  "examples/rocket",
  "examples/raw",
  "tokio-postgres-tang",
  "redis-tang",
  "mongodb-tang"
]

[dev-dependencies.async-std]
version = "1.5.0"
features = ["attributes", "unstable"]
