[package]
name = "basic_example"
version = "0.1.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies.tang-rs]
path = "../../"

[dependencies.async-std]
version = "1.6.0"
features = ["attributes", "unstable"]

[dependencies.smol]
version = "0.1.10"