[package]
name = "basic"
version = "0.1.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies.tang-rs]
path = "../../"

[dependencies.async-std]
version = "1.5.0"
features = ["attributes", "unstable"]