[package]
name = "basic"
version = "0.1.0"
authors = ["fakeshadow <24548779@qq.com>"]
edition = "2018"

[dependencies.tang-rs]
path = "../../"

[dependencies.async-std]
version = "1.5.0"
features = ["attributes", "unstable"]